{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.firebase",
    "module": "firebase-crashlytics-buildtools",
    "version": "3.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase-crashlytics-buildtools-3.0.5.jar",
          "url": "firebase-crashlytics-buildtools-3.0.5.jar",
          "size": 8437846,
          "sha512": "854db9ec79329ad5ddd7305d11bca2fa0111ad1c83e697501c8f0b12efa34b726d26dba95057e041db12d942238c0205c6a05992cb351927ec9e4d9d22f87b33",
          "sha256": "7149277cb3aaf8cd7e0acb1f17379b8c65c40b08f71bc7c2b9cae16ff90dc13b",
          "sha1": "b28e3aaf86ee12c01c6d30580246fa61f6c75104",
          "md5": "aad4b4b6328e189b1f6677d335bd1cfc"
        }
      ]
    }
  ]
}
